sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download google sdk and install it locally on our little instance that is assigned to us by travisCI
  - source $HOME/google-cloud-sdk/path.bash.inc # there are some configuration taht is going to modify our shell inside of TravisCI inside this file and we are going to apply that additional conf through the source command 
  - gcloud components update kubectl #use updated kubectl to apply all those different conf files
  - gcloud auth activate-service-account --key-file service-account.json #this is who we are and here is our password or whatever it might be, everything that it needs to actually log in and get access to our account
  - 
  